/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinutesRouteImport } from './routes/minutes'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinutesRoute = MinutesRouteImport.update({
  id: '/minutes',
  path: '/minutes',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minutes': typeof MinutesRoute
  '/prompts': typeof PromptsRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minutes': typeof MinutesRoute
  '/prompts': typeof PromptsRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minutes': typeof MinutesRoute
  '/prompts': typeof PromptsRoute
  '/api/generate': typeof ApiGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/minutes' | '/prompts' | '/api/generate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/minutes' | '/prompts' | '/api/generate'
  id: '__root__' | '/' | '/minutes' | '/prompts' | '/api/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinutesRoute: typeof MinutesRoute
  PromptsRoute: typeof PromptsRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minutes': {
      id: '/minutes'
      path: '/minutes'
      fullPath: '/minutes'
      preLoaderRoute: typeof MinutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinutesRoute: MinutesRoute,
  PromptsRoute: PromptsRoute,
  ApiGenerateRoute: ApiGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
